package.json: Update Parcel.js to 2.5.0
This resolves the incompatibility with Fomantic UI 2.8.8, which was the
rationale why we constrained Parcel.js to <2.4 (see a0ed3df), AND this
new error:

TypeError: Cannot read properties of undefined (reading 'open')
    at new LMDBCache
(/home/michael/Documents/Freizeit/Programme/python/shc2/node_modules/@parcel/cache/lib/LMDBCache.js:69:33)